import type { GeneratedCard } from "@/types";

/**
 * Calculate Levenshtein distance between two strings.
 * Measures the minimum number of single-character edits needed to transform one string into another.
 * Lower distance = higher similarity.
 */
function levenshteinDistance(s1: string, s2: string): number {
  const m = s1.length;
  const n = s2.length;

  if (m === 0) return n;
  if (n === 0) return m;

  const dp: number[][] = Array.from({ length: m + 1 }, (_, i) => [i]);
  for (let j = 1; j <= n; j++) {
    dp[0][j] = j;
  }

  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      const cost = s1[i - 1] === s2[j - 1] ? 0 : 1;
      dp[i][j] = Math.min(
        dp[i - 1][j] + 1, // deletion
        dp[i][j - 1] + 1, // insertion
        dp[i - 1][j - 1] + cost, // substitution
      );
    }
  }

  return dp[m][n];
}

/**
 * Normalize Levenshtein distance to a similarity score (0–1).
 * Score of 1.0 = identical; 0.0 = completely different.
 */
function levenshteinSimilarity(s1: string, s2: string): number {
  if (s1.length === 0 && s2.length === 0) {
    return 1.0;
  }

  const maxLength = Math.max(s1.length, s2.length);
  const distance = levenshteinDistance(s1.toLowerCase(), s2.toLowerCase());

  return 1.0 - distance / maxLength;
}

/**
 * Compare a generated card against a list of reference cards.
 * Returns the best matching score (highest similarity).
 *
 * @param generatedCard - Card generated by AI
 * @param referenceCards - List of expected cards to compare against
 * @returns Similarity score (0–1), where 1.0 is a perfect match
 */
export function calculateSimilarity(generatedCard: GeneratedCard, referenceCards: GeneratedCard[]): number {
  if (referenceCards.length === 0) {
    return 0;
  }

  // Compare both front and back; average the scores
  const scores = referenceCards.map((refCard) => {
    const frontSim = levenshteinSimilarity(generatedCard.front, refCard.front);
    const backSim = levenshteinSimilarity(generatedCard.back, refCard.back);
    // Weight front (question) slightly higher than back (answer)
    return frontSim * 0.6 + backSim * 0.4;
  });

  // Return the best match
  return Math.max(...scores);
}

/**
 * Calculate average similarity between a list of generated cards and reference cards.
 *
 * @param generatedCards - Cards generated by AI
 * @param referenceCards - Expected cards for comparison
 * @returns Average similarity score (0–1)
 */
export function calculateAverageSimilarity(generatedCards: GeneratedCard[], referenceCards: GeneratedCard[]): number {
  if (generatedCards.length === 0) {
    return 0;
  }

  const scores = generatedCards.map((card) => calculateSimilarity(card, referenceCards));
  const sum = scores.reduce((a, b) => a + b, 0);
  return sum / scores.length;
}
